name: Build & Deploy

on:
  push:
    branches: [main]

env:
  USER_PASS: ${{secrets.USER_PASSWD}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Deploy website
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          envs: USER_PASS

          script: |
            . ./deploy.sh
            echo 'Deployment successful'
