name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd /var/www/jacobspeicher.com/personal-website
            SUDO_ASKPASS="~/pass" sudo -A git pull
            SUDO_ASKPASS="~/pass" sudo -A npm run build
            echo 'Deployment successful'
