name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Deploy website
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{secrets.SSH_HOST}}
          privateKey: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          local: ./src/assets
          remote: ~/copied
